### PR TITLE
donarregister

### LINKED ISSUE #11: To implement assign donors functionality
Definition of done:
Admin should be able to assign donors to the agents.

### PR DESCRIPTION
**Pull request by SuyesSapkota**
View function for handling the submission of a donor registration form, including form validation, saving the form data, and redirecting to a success page

### CODE REVIEW

**Comment by Temporary-summer** [comment]
Could you please consider incorporating the principles of Program By Contract and Literate Programming into your coding ?

**Comment by SuyesSapkota** [comment]
Updated code incorporating Program By Contract and Literate Programming principles.

**Comment by Temporary-summer** [comment]
I looked into it and its good to be merged.

**Review by Temporary-summer — APPROVED** [review]
I have looked into it you have made the necessary changes  as discussed. so, its good to be merged now

**Pull request merged**
